### ISSUE TITLE
page names to ENGLSIH

### ISSUE THREAD

**Issue by adam4h** [yonglas-surfcode/MinhalFhill#49]
page name:  (englsih)
MenuItemName: (hebrew)

Need to update:
1) transformations
2) newsletters macros
3) web part paths

**Comment by yonglas-surfcode** [comment]
this pages are ready:
Home
About
Calendar
Video Gallery
Image Gallery
Contact-Us

Business - need to fix this green results link
http://dev.adamgitin.com/Business?searchtext=%D7%91%D7%A0%D7%A7&searchmode=anyword
